let divisions = [
  {
    name: "Dhaka",
    districts: [
      {
        name: "Dhaka",
        upzillas: [
          "Dhaka",
          "Savar",
          "Dhamrai",
          "Dohar",
          "Keraniganj",
          "Nawabganj",
          "Tongi",
        ],
      },
      {
        name: "Faridpur",
        upzillas: [
          "Faridpur",
          "Alfadanga",
          "Bhanga",
          "Boalmari",
          "Charbhadrasan",
          "Madhukhali",
          "Nagarkanda",
          "Sadarpur",
          "Shaltha",
        ],
      },
      {
        name: "Gazipur",
        upzillas: ["Gazipur Sadar", "Kaliakair", "Kapasia", "Sreepur"],
      },
      {
        name: "Gopalganj",
        upzillas: [
          "Gopalganj Sadar",
          "Kashiani",
          "Kotalipara",
          "Muksudpur",
          "Tungipara",
        ],
      },
      {
        name: "Kishoreganj",
        upzillas: [
          "Austagram",
          "Bajitpur",
          "Bhairab",
          "Hossainpur",
          "Itna",
          "Karimganj",
          "Katiadi",
          "Kishoreganj Sadar",
          "Kuliarchar",
          "Mithamain",
          "Nikli",
          "Pakundia",
          "Tarail",
        ],
      },
      {
        name: "Madaripur",
        upzillas: ["Barishal", "Kalkini", "Madaripur Sadar", "Rajoir"],
      },
      {
        name: "Manikganj",
        upzillas: [
          "Daulatpur",
          "Ghior",
          "Harirampur",
          "Manikganj Sadar",
          "Saturia",
          "Shibalaya",
          "Singair",
        ],
      },
      {
        name: "Munshiganj",
        upzillas: [
          "Gazaria",
          "Lohajang",
          "Munshiganj Sadar",
          "Sirajdikhan",
          "Sreenagar",
          "Tongibari",
        ],
      },
      {
        name: "Narayanganj",
        upzillas: [
          "Araihazar",
          "Baidder Bazar",
          "Bandar",
          "Fatulla",
          "Narayanganj Sadar",
          "Rupganj",
          "Sonargaon",
        ],
      },
      {
        name: "Narsingdi",
        upzillas: [
          "Belabo",
          "Monohardi",
          "Narsingdi Sadar",
          "Palash",
          "Raipura",
          "Shibpur",
        ],
      },
      {
        name: "Rajbari",
        upzillas: ["Baliakandi", "Goalandaghat", "Pangsha", "Rajbari Sadar"],
      },
      {
        name: "Shariatpur",
        upzillas: [
          "Bhedarganj",
          "Damudya",
          "Gosairhat",
          "Jajira",
          "Naria",
          "Shariatpur Sadar",
          "Zanjira",
        ],
      },
      {
        name: "Tangail",
        upzillas: [
          "Basail",
          "Bhuapur",
          "Delduar",
          "Ghatail",
          "Gopalpur",
          "Kalihati",
          "Madhupur",
          "Mirzapur",
          "Nagarpur",
          "Sakhipur",
          "Tangail Sadar",
        ],
      },
    ],
  },
  {
    name: "Chittagong",
    districts: [
      {
        name: "Chittagong",
        upzillas: [
          "Anwara",
          "Banshkhali",
          "Boalkhali",
          "Chandanaish",
          "Fatikchhari",
          "Hathazari",
          "Lohagara",
          "Mirsharai",
          "Patiya",
          "Rangunia",
          "Raozan",
          "Sandwip",
          "Satkania",
          "Sitakunda",
        ],
      },
      {
        name: "Cox's Bazar",
        upzillas: [
          "Chakaria",
          "Cox's Bazar Sadar",
          "Maheshkhali",
          "Pekua",
          "Ramu",
          "Teknaf",
          "Ukhia",
        ],
      },
      {
        name: "Comilla",
        upzillas: [
          "Barura",
          "Brahmanpara",
          "Burichang",
          "Chandina",
          "Chauddagram",
          "Comilla Sadar Dakshin",
          "Comilla Sadar Uttar",
          "Daudkandi",
          "Davidhar",
          "Debidwar",
          "Homna",
          "Laksam",
          "Muradnagar",
          "Nangalkot",
          "Titas",
        ],
      },
      {
        name: "Brahmanbaria",
        upzillas: [
          "Akhaura",
          "Ashuganj",
          "Bancharampur",
          "Bijoynagar",
          "Brahmanbaria Sadar",
          "Kasba",
          "Nabinagar",
          "Nasirnagar",
          "Sarail",
        ],
      },
      {
        name: "Feni",
        upzillas: [
          "Chhagalnaiya",
          "Daganbhuiyan",
          "Feni Sadar",
          "Parshuram",
          "Sonagazi",
        ],
      },
      {
        name: "Khagrachhari",
        upzillas: [
          "Dighinala",
          "Khagrachhari Sadar",
          "Laxmichhari",
          "Mahalchhari",
          "Manikchhari",
          "Matiranga",
          "Panchhari",
          "Ramgarh",
        ],
      },
      {
        name: "Bandarban",
        upzillas: [
          "Ali Kadam",
          "Bandarban Sadar",
          "Lama",
          "Rowangchhari",
          "Ruma",
          "Thanchi",
        ],
      },
      {
        name: "Rangamati",
        upzillas: [
          "Baghaichhari",
          "Barkal",
          "Kaptai",
          "Juraichhari",
          "Rajasthali",
          "Rangamati Sadar",
        ],
      },
      {
        name: "Noakhali",
        upzillas: [
          "Begumganj",
          "Chatkhil",
          "Companiganj",
          "Hatiya",
          "Noakhali Sadar",
          "Senbagh",
          "Subarnachar",
        ],
      },
      {
        name: "Lakshmipur",
        upzillas: [
          "Char Alexanda",
          "Ramganj",
          "Kamalnagar",
          "Lakshmipur Sadar",
          "Raipur",
          "Ramgati",
        ],
      },
      {
        name: "Chandpur",
        upzillas: [
          "Chandpur Sadar",
          "Hajiganj",
          "Kachua",
          "Matlab Dakkhin",
          "Matlab Uttar",
          "Shahrasti",
        ],
      },
      {
        name: "Bhola",
        upzillas: [
          "Bhola Sadar",
          "Burhanuddin",
          "Char Fasson",
          "Daulatkhan",
          "Lalmohan",
          "Manpura",
          "Tazumuddin",
        ],
      },
    ],
  },
  {
    name: "Rajshahi",
    districts: [
      {
        name: "Rajshahi",
        upzillas: [
          "Bagha",
          "Bagmara",
          "Charghat",
          "Durgapur",
          "Godagari",
          "Mohanpur",
          "Paba",
          "Puthia",
          "Tanore",
        ],
      },
      {
        name: "Naogaon",
        upzillas: [
          "Atrai",
          "Badalgachhi",
          "Dhamoirhat",
          "Manda",
          "Mohadevpur",
          "Naogaon Sadar",
          "Niamatpur",
          "Patnitala",
          "Porsha",
          "Raninagar",
          "Sapahar",
        ],
      },
      {
        name: "Natore",
        upzillas: [
          "Bagatipara",
          "Baraigram",
          "Gurudaspur",
          "Lalpur",
          "Natore Sadar",
          "Singra",
        ],
      },
      {
        name: "Chapainawabganj",
        upzillas: [
          "Bholahat",
          "Chapainawabganj Sadar",
          "Gomastapur",
          "Nachole",
          "Shibganj",
        ],
      },
      {
        name: "Pabna",
        upzillas: [
          "Atgharia",
          "Bera",
          "Bhangura",
          "Chatmohar",
          "Faridpur",
          "Ishwardi",
          "Pabna Sadar",
          "Santhia",
          "Sujanagar",
        ],
      },
      {
        name: "Joypurhat",
        upzillas: [
          "Akkelpur",
          "Joypurhat Sadar",
          "Kalai",
          "Khetlal",
          "Panchbibi",
        ],
      },
      {
        name: "Bogra",
        upzillas: [
          "Adamdighi",
          "Bogra Sadar",
          "Dhunat",
          "Dhupchanchia",
          "Gabtali",
          "Kahaloo",
          "Nandigram",
          "Sariakandi",
          "Sherpur",
          "Shibganj",
          "Sonatola",
        ],
      },
      {
        name: "Sirajganj",
        upzillas: [
          "Belkuchi",
          "Chauhali",
          "Kamarkhanda",
          "Kazipur",
          "Raiganj",
          "Shahjadpur",
          "Sirajganj Sadar",
          "Tarash",
          "Ullahpara",
        ],
      },
      {
        name: "Bogra",
        upzillas: [
          "Adamdighi",
          "Bogra Sadar",
          "Dhunat",
          "Dhupchanchia",
          "Gabtali",
          "Kahaloo",
          "Nandigram",
          "Sariakandi",
          "Sherpur",
          "Shibganj",
          "Sonatola",
        ],
      },
    ],
  },
  {
    name: "Khulna",
    districts: [
      {
        name: "Khulna",
        upzillas: [
          "Batiaghata",
          "Dacope",
          "Dumuria",
          "Dighalia",
          "Koyra",
          "Paikgachha",
          "Phultala",
          "Rupsa",
          "Terokhada",
        ],
      },
      {
        name: "Jessore",
        upzillas: [
          "Abhaynagar",
          "Bagherpara",
          "Chaugachha",
          "Jessore Sadar",
          "Jhikargachha",
          "Keshabpur",
          "Manirampur",
          "Sharsha",
        ],
      },
      {
        name: "Satkhira",
        upzillas: [
          "Assasuni",
          "Debhata",
          "Kalaroa",
          "Kaliganj",
          "Satkhira Sadar",
          "Shyamnagar",
          "Tala",
        ],
      },
      {
        name: "Kushtia",
        upzillas: [
          "Bheramara",
          "Daulatpur",
          "Khoksa",
          "Kumarkhali",
          "Kushtia Sadar",
          "Mirpur",
          "Rafayetpur",
        ],
      },
      {
        name: "Magura",
        upzillas: [
          "Magura Sadar",
          "Mohammadpur",
          "Salikha",
          "Shalikha",
          "Sreepur",
        ],
      },
      {
        name: "Meherpur",
        upzillas: ["Gangni", "Mujibnagar", "Meherpur Sadar"],
      },
      {
        name: "Narail",
        upzillas: ["Kalia", "Lohagara", "Narail Sadar"],
      },
      {
        name: "Chuadanga",
        upzillas: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
      },
      {
        name: "Bagerhat",
        upzillas: [
          "Bagerhat Sadar",
          "Chitalmari",
          "Fakirhat",
          "Kachua",
          "Mollahat",
          "Mongla",
          "Morrelganj",
          "Rampal",
          "Sarankhola",
        ],
      },
    ],
  },
  {
    name: "Barishal",
    districts: [
      {
        name: "Barishal",
        upzillas: [
          "Agailjhara",
          "Babuganj",
          "Bakerganj",
          "Banaripara",
          "Gaurnadi",
          "Hizla",
          "Muladi",
          "Barishal Sadar",
          "Mehendiganj",
          "Wazirpur",
        ],
      },
      {
        name: "Barguna",
        upzillas: [
          "Amtali",
          "Bamna",
          "Barguna Sadar",
          "Betagi",
          "Patharghata",
          "Taltali",
        ],
      },
      {
        name: "Bhola",
        upzillas: [
          "Bhola Sadar",
          "Burhanuddin",
          "Char Fasson",
          "Daulatkhan",
          "Lalmohan",
          "Manpura",
          "Tazumuddin",
        ],
      },
      {
        name: "Jhalokati",
        upzillas: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
      },
      {
        name: "Patuakhali",
        upzillas: [
          "Bauphal",
          "Dasmina",
          "Galachipa",
          "Kalapara",
          "Mirzaganj",
          "Patuakhali Sadar",
          "Rangabali",
          "Dumki",
        ],
      },
      {
        name: "Pirojpur",
        upzillas: [
          "Bhandaria",
          "Kaukhali",
          "Mathbaria",
          "Nazirpur",
          "Nesarabad (Swarupkathi)",
          "Pirojpur Sadar",
          "Zianagar",
        ],
      },
    ],
  },
  {
    name: "Sylhet",
    districts: [
      {
        name: "Habiganj",
        upzillas: [
          "Habiganj Sadar",
          "Ajmiriganj",
          "Bahubal",
          "Baniachang",
          "Chunarughat",
          "Lakhai",
          "Madhabpur",
          "Nabiganj",
        ],
      },
      {
        name: "Moulvibazar",
        upzillas: [
          "Moulvibazar Sadar",
          "Barlekha",
          "Juri",
          "Kamalganj",
          "Kulaura",
          "Rajnagar",
          "Sreemangal",
        ],
      },
      {
        name: "Sunamganj",
        upzillas: [
          "Sunamganj Sadar",
          "Bishwamvarpur",
          "Chhatak",
          "Dakshin Sunamganj",
          "Dharampasha",
          "Duara bazar",
          "Jagnnathpur",
          "Jamalganj",
          "Shalla",
          "Tahirpur",
          "Tahirpur",
        ],
      },
      {
        name: "Sylhet",
        upzillas: [
          "Balaganj",
          "Beanibazar",
          "Bishwanath",
          "Companiganj",
          "Dakshin Surma",
          "Fenchuganj",
          "Golapganj",
          "Gowainghat",
          "Jaintiapur",
          "Kanaighat",
          "Zakiganj",
        ],
      },
    ],
  },
  {
    name: "Rangpur",
    districts: [
      {
        name: "Rangpur",
        upzillas: [
          "Badarganj",
          "Gangachara",
          "Kaunia",
          "Mithapukur",
          "Pirgachha",
          "Pirganj",
          "Rangpur Sadar",
          "Taraganj",
        ],
      },
      {
        name: "Kurigram",
        upzillas: [
          "Bhurungamari",
          "Chilmari",
          "Phulbari",
          "Kurigram Sadar",
          "Nageshwari",
          "Rajarhat",
          "Raumari",
          "Ulipur",
        ],
      },
      {
        name: "Lalmonirhat",
        upzillas: [
          "Aditmari",
          "Hatibandha",
          "Kaliganj",
          "Lalmonirhat Sadar",
          "Patgram",
        ],
      },
      {
        name: "Nilphamari",
        upzillas: [
          "Dimla",
          "Domar",
          "Jaldhaka",
          "Kishoreganj",
          "Nilphamari Sadar",
          "Saidpur",
        ],
      },
      {
        name: "Gaibandha",
        upzillas: [
          "Fulchari",
          "Gaibandha Sadar",
          "Gobindaganj",
          "Palashbari",
          "Sadullapur",
          "Saghata",
          "Sundarganj",
        ],
      },
      {
        name: "Kurigram",
        upzillas: [
          "Bhurungamari",
          "Chilmari",
          "Phulbari",
          "Kurigram Sadar",
          "Nageshwari",
          "Rajarhat",
          "Raumari",
          "Ulipur",
        ],
      },
      {
        name: "Thakurgaon",
        upzillas: [
          "Baliadangi",
          "Haripur",
          "Pirganj",
          "Ranisankail",
          "Thakurgaon Sadar",
        ],
      },
      {
        name: "Panchagarh",
        upzillas: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
      },
    ],
  },
];
export default divisions;
